Bail out as soon as processing of a mailbox fails
Signed-off-by: Frank Terbeck <ft@bewatermyfriend.org>

diff --git a/zsh-am b/zsh-am
--- a/zsh-am
+++ b/zsh-am
@@ -96,7 +96,10 @@ if should_try_stdin; then
     }
 else
     for mbox in "$@"; do
-        process_mbox "$mbox"
+        process_mbox "$mbox" || {
+            echo "zsh-am: Processing mailbox failed: \"$mbox\"; Exiting..."
+            exit 1
+        }
     done
 fi
 exit 0
